### ISSUE TITLE
Add a 'create task' feature.

### ISSUE THREAD

**Issue by Timaert** [Timaert/Anticipate#1]
# Adding a 'create task' feature
## Progress
- [ ] Create a data structure for storing tasks.
- [ ] Store the tasks on the user's system.
- [ ] Implement the new flag.
- [ ] Implement the date flag.
- [ ] Implement the time flag.
- [ ] Implement the priority level flag.
- [ ] Implement the label flag.
- [ ] Write tests for this feature.
- [ ] Write documentation for this feature.

### Tasks
There are a number of things a task should store information about.
- name
- due date (optional)
- time (optional)
- priority level (optional, high, medium and low)
- label (optional, predefined or custom, see the feature request for labels)
- description (optional, see the feature request for descriptions)
- checklist (optional, for more information see the feature request for checklists)

Descriptions and checklists are a task configuration option and can't be passed in through the create command.

### Task Creation
Upon issuing the create command the user will receive a short questionnaire if they did not specify the necessary information from the start. 

#### Name
The user can provide a name for the task, this is a pretty self-explanatory feature.
```
anticipate create -n call mom
anticipate create -n clean the kitchen
```

If the user does not provide this flag, the question shown will be:
```
What name should your task have? (eg. clean the kitchen):
$ call mom
```

#### Due Date (optional)
Due dates are provided in two ways. Using the first method the user can specify a day of the week prefixed by a modifier such as 'next' or suffixed by a modifier along the lines of 'in two weeks'. A suffix can be used in a standalone way as well, it will just use the current day instead of a user specified one
```
anticipate create -n call mom -d tomorrow
anticipate create -n clean the kitchen -d next week
anticipate create -n dentist appointment -d monday in two weeks
anticipate create -n get the car fixed -d in two weeks
```

The second method is to provide a day and month number. By default it will use the European day/month convention. We can provide a configuration option to enable the month/day convention used in the US. There is no need to provide the year, it wraps around to the next year automatically.
```
anticipate create -n call mom -d 18/10
anticipate create -n clean the kitchen -d 9/8
anticipate create -n dentist appointment -d 20/12
anticipate create -n get the car fixed -d 25/3
```

If the user does not provide this flag, the question shown will be:
```
When is this date due? (optional, eg. monday in two weeks, or 20/7):
$ tomorrow
```

#### Time (optional)
The user can optionally provide the time at which a certain task should be completed. Again 24-hour based by European convention with an option to change to the US conventions.
```
anticipate create -t 12:30
anticipate create -t 17:45
```

If the user does not provide this flag, the question shown will be:
```
At what time should your task be completed? (optional):
$ <return>

At what time should your task be completed? (optional):
$ 14:30
```

#### Priority (optional)
You can provide a priority to the task by passing either low, medium or high to the -p flag.
```
anticipate create -p high
anticipate create -p low
```

If the user does not provide this flag, the question shown will be:
```
What priority does this task have? (optional):
$ <return>

What priority does this task have? (optional):
$ high
```

#### Label (optional)
The user can also provide a label to help identify this task. please check the label feature request for details
```
anticipate create -l school
anticipate create -l work
```

If the user does not provide this flag, the question shown will be:
```
What label does this task have? (optional, eg. school or work):
$ <return>

What label does this task have? (optional, eg. school or work):
$ school
```

## Usage
```
anticipate create [-n <task name>] [-d <due>] [-t <time>] [-p <priority>] [-l <label>]
```
